name: Generate Zombie Survival Graph

on:
  schedule:
    - cron: "0 0 * * *" # Her gece yarısı otomatik çalışır
  workflow_dispatch:    # Manuel tetikleme butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        run: pip install requests python-dotenv
        
      - name: Generate Zombie Graph
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }} # Repoyu kim kurduysa onun ismini çeker
          GAME_START_DATE: "2026-08-15" # Başkaları kurarken bu tarihi değiştirecek
        run: python zombie.py
        
      - name: Commit & Push Generated Graph
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add zombi-grafik.svg
          git commit -m "update: Daily Zombie Survival Intel" || echo "No changes to commit"
          git push